### ISSUE TITLE
Automation Action

### ISSUE THREAD

**Issue by kozfelipe** [yangqian/hass-cozylife#10]
How can I use these lights in HA automation action?
I want to turn off all the lights when I leave home
I tried using Device option but cozylife discover only insert a entity rather than a device.
I tried using Service option but I only have these 2 services available:
* cozylife: Set all effect
* cozylife: Set effect

is there a way to turn a light off by automation?

**Comment by yangqian** [comment]
Just something like:
````yaml
  - service: light.turn_on
    target:
      entity_id: light.bedroom
```

    cozylife: Set all effect
    cozylife: Set effect
are used to set the effect while the light is still off.
