### ISSUE TITLE
How to add the integration?

### ISSUE THREAD

**Issue by miguelpucela** [yangqian/hass-cozylife#18]
I think the instructions are not sufficiently clear, or I miss somthing.

I follow these steps to set up the integration:

- In HACS, add custom repository: https://github.com/yangqian/hass-cozylife
- Explore and Download Repositories: Cozylife -> Download
- Restart HA
- I execute:  py getconfig.py 10.11.12.198 10.11.12.200
and get

```
lights:
- platform: cozylife
  lights:
  - ip: 10.11.12.199
    did: 671630877cb94cb41bcd
    pid: d50v0i
    dmn: Music Rhythm Light Strip
    dpid: [1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14]
    device_type: 01

switch:
- platform: cozylife
  switches:
```

- I copy these lines to my configuration.yaml

After this, I get next error:

```
Invalid config
The following integrations and platforms could not be set up:

lights (Show logs)
```

In the logs:

```
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 19:03:06 (1 occurrences)
Last logged: 19:03:06

Setup failed for 'lights': Integration not found.
```

I've also tried to add:
`hass-cozylife:`
or
`cozylife:`
or
`hass_cozylife_local_pull:`

to configuration.yaml without success.

What am I missing?
Thanks!

**Comment by dbaines** [comment]
@miguelpucela the first line should be `light:` not `lights:`

**Comment by miguelpucela** [comment]
I've tried with `light:` but the logs give me this error:

```
Logger: homeassistant.config
Source: config.py:1195
First occurred: 10:07:46 (1 occurrences)
Last logged: 10:07:46

Invalid config for 'light.cozylife' at configuration.yaml, line 482: 'device_type' is an invalid option for 'light.cozylife', check: lights->0->device_type, please check the docs at https://github.com/yangqian/hass-cozylife
```

BTW, the `lights:` is the output of the script getconfig.py. It should be changed with `light:` there.

Then, the script getconfig.py should be changed to write "lights"

> @miguelpucela the first line should be `light:` not `lights:`

**Comment by dbaines** [comment]
Also remove that line it's not needed according to the readme:

```
light:
- platform: cozylife
  lights:
  - ip: 192.168.1.193
    did: 637929887cb94c4cffff
    pid: p93sfg
    dmn: Smart Bulb Light
    dpid: [1, 2, 3, 4, 5, 7, 8, 9, 13, 14]
  - ip: 192.168.1.194
    did: 637929887cb94c4ceeee
    pid: p93sfg
    dmn: Smart Bulb Light
    dpid: [1, 2, 3, 4, 5, 7, 8, 9, 13, 14]
```

I integrated one today, following that format in the readme worked fine for me.
