### ISSUE TITLE
Configuration needed in configuration.yaml?

### ISSUE THREAD

**Issue by PauloGoncalves86** [yangqian/hass-cozylife#34]
I started trying to use this integration for a couple of switches, having deinstalled the official but dead [cozylife](https://github.com/cozylife)
[hass_cozylife_local_pull](https://github.com/cozylife/hass_cozylife_local_pull) first. 

Is the below also required in the configuration.yaml?

Or is the header meant to be "cozylife"?

hass_cozylife_local_pull:
   lang: en
   ip:
     - 192.168.x.x - <homeassistant_ip?>

**Comment by lmarcelocc** [comment]
Olá Paulo,

I'm using this repo and what I did was to install it from HACS and then I run the python script - sometimes it works, sometimes won't - it helped me if I'm connected to a 2.4Ghz Wifi.


If it find something, script will output what you need to paste at your configuration.yaml, something like:
```yaml
light:
- platform: cozylife
  lights:
  - ip: 192.168.1.193
    did: 637929887cb94c4cffff
    pid: p93sfg
    dmn: Smart Bulb Light
    dpid: [1, 2, 3, 4, 5, 7, 8, 9, 13, 14]
  - ip: 192.168.1.194
    did: 637929887cb94c4ceeee
    pid: p93sfg
    dmn: Smart Bulb Light
    dpid: [1, 2, 3, 4, 5, 7, 8, 9, 13, 14]
```

What I've besides that is this:
```yaml
switch:
- platform: cozylife
  switches:
```



Boa sorte :)
